// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class Capacity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject capacityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.Capacity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Avability("Avability"),
		Remaining_Avail("Remaining_Avail"),
		total("total"),
		Capacity_Employee("CCGProjectTracking.Capacity_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Capacity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.Capacity"));
	}

	protected Capacity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject capacityMendixObject)
	{
		if (capacityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.Capacity", capacityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.Capacity");

		this.capacityMendixObject = capacityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Capacity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.Capacity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.Capacity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.Capacity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.Capacity(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.Capacity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.Capacity.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.Capacity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Capacity> result = new java.util.ArrayList<ccgprojecttracking.proxies.Capacity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.Capacity" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.Capacity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Avability
	 */
	public final java.math.BigDecimal getAvability()
	{
		return getAvability(getContext());
	}

	/**
	 * @param context
	 * @return value of Avability
	 */
	public final java.math.BigDecimal getAvability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Avability.toString());
	}

	/**
	 * Set value of Avability
	 * @param avability
	 */
	public final void setAvability(java.math.BigDecimal avability)
	{
		setAvability(getContext(), avability);
	}

	/**
	 * Set value of Avability
	 * @param context
	 * @param avability
	 */
	public final void setAvability(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal avability)
	{
		getMendixObject().setValue(context, MemberNames.Avability.toString(), avability);
	}

	/**
	 * @return value of Remaining_Avail
	 */
	public final java.math.BigDecimal getRemaining_Avail()
	{
		return getRemaining_Avail(getContext());
	}

	/**
	 * @param context
	 * @return value of Remaining_Avail
	 */
	public final java.math.BigDecimal getRemaining_Avail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Remaining_Avail.toString());
	}

	/**
	 * Set value of Remaining_Avail
	 * @param remaining_avail
	 */
	public final void setRemaining_Avail(java.math.BigDecimal remaining_avail)
	{
		setRemaining_Avail(getContext(), remaining_avail);
	}

	/**
	 * Set value of Remaining_Avail
	 * @param context
	 * @param remaining_avail
	 */
	public final void setRemaining_Avail(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal remaining_avail)
	{
		getMendixObject().setValue(context, MemberNames.Remaining_Avail.toString(), remaining_avail);
	}

	/**
	 * @return value of total
	 */
	public final java.math.BigDecimal gettotal()
	{
		return gettotal(getContext());
	}

	/**
	 * @param context
	 * @return value of total
	 */
	public final java.math.BigDecimal gettotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.total.toString());
	}

	/**
	 * Set value of total
	 * @param total
	 */
	public final void settotal(java.math.BigDecimal total)
	{
		settotal(getContext(), total);
	}

	/**
	 * Set value of total
	 * @param context
	 * @param total
	 */
	public final void settotal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal total)
	{
		getMendixObject().setValue(context, MemberNames.total.toString(), total);
	}

	/**
	 * @return value of Capacity_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getCapacity_Employee() throws com.mendix.core.CoreException
	{
		return getCapacity_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Capacity_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getCapacity_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Capacity_Employee.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Capacity_Employee
	 * @param capacity_employee
	 */
	public final void setCapacity_Employee(ccgprojecttracking.proxies.Employee capacity_employee)
	{
		setCapacity_Employee(getContext(), capacity_employee);
	}

	/**
	 * Set value of Capacity_Employee
	 * @param context
	 * @param capacity_employee
	 */
	public final void setCapacity_Employee(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee capacity_employee)
	{
		if (capacity_employee == null)
			getMendixObject().setValue(context, MemberNames.Capacity_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Capacity_Employee.toString(), capacity_employee.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return capacityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.Capacity that = (ccgprojecttracking.proxies.Capacity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.Capacity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
