// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class Enhancement
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject enhancementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.Enhancement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Enh_ID("Enh_ID"),
		Enhancement_Description("Enhancement_Description"),
		TypeOfReqirement("TypeOfReqirement"),
		Project_Type("Project_Type"),
		Project_Created_Date("Project_Created_Date"),
		Project_Started_Date("Project_Started_Date"),
		Project_Published_Date("Project_Published_Date"),
		ETA_Date("ETA_Date"),
		Project_End_Date("Project_End_Date"),
		Project_CreatedBy("Project_CreatedBy"),
		Project_Modified_Date("Project_Modified_Date"),
		Project_ModifiedBy("Project_ModifiedBy"),
		ESR_Id("ESR_Id"),
		Current_Phase("Current_Phase"),
		Project_status("Project_status"),
		Latest_Published_Date("Latest_Published_Date"),
		SME("SME"),
		Project_Owner("Project_Owner"),
		Enhancement_Task("CCGProjectTracking.Enhancement_Task"),
		Enhancement_ProjectDetails("CCGProjectTracking.Enhancement_ProjectDetails");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Enhancement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.Enhancement"));
	}

	protected Enhancement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject enhancementMendixObject)
	{
		if (enhancementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.Enhancement", enhancementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.Enhancement");

		this.enhancementMendixObject = enhancementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Enhancement.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.Enhancement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.Enhancement.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.Enhancement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.Enhancement(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.Enhancement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.Enhancement.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.Enhancement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Enhancement> result = new java.util.ArrayList<ccgprojecttracking.proxies.Enhancement>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.Enhancement" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.Enhancement.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Enh_ID
	 */
	public final java.lang.String getEnh_ID()
	{
		return getEnh_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Enh_ID
	 */
	public final java.lang.String getEnh_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Enh_ID.toString());
	}

	/**
	 * Set value of Enh_ID
	 * @param enh_id
	 */
	public final void setEnh_ID(java.lang.String enh_id)
	{
		setEnh_ID(getContext(), enh_id);
	}

	/**
	 * Set value of Enh_ID
	 * @param context
	 * @param enh_id
	 */
	public final void setEnh_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enh_id)
	{
		getMendixObject().setValue(context, MemberNames.Enh_ID.toString(), enh_id);
	}

	/**
	 * @return value of Enhancement_Description
	 */
	public final java.lang.String getEnhancement_Description()
	{
		return getEnhancement_Description(getContext());
	}

	/**
	 * @param context
	 * @return value of Enhancement_Description
	 */
	public final java.lang.String getEnhancement_Description(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Enhancement_Description.toString());
	}

	/**
	 * Set value of Enhancement_Description
	 * @param enhancement_description
	 */
	public final void setEnhancement_Description(java.lang.String enhancement_description)
	{
		setEnhancement_Description(getContext(), enhancement_description);
	}

	/**
	 * Set value of Enhancement_Description
	 * @param context
	 * @param enhancement_description
	 */
	public final void setEnhancement_Description(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String enhancement_description)
	{
		getMendixObject().setValue(context, MemberNames.Enhancement_Description.toString(), enhancement_description);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param typeofreqirement
	 */
	public final ccgprojecttracking.proxies.TYR getTypeOfReqirement()
	{
		return getTypeOfReqirement(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeOfReqirement
	 */
	public final ccgprojecttracking.proxies.TYR getTypeOfReqirement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeOfReqirement.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.TYR.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param typeofreqirement
	 */
	public final void setTypeOfReqirement(ccgprojecttracking.proxies.TYR typeofreqirement)
	{
		setTypeOfReqirement(getContext(), typeofreqirement);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param context
	 * @param typeofreqirement
	 */
	public final void setTypeOfReqirement(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.TYR typeofreqirement)
	{
		if (typeofreqirement != null)
			getMendixObject().setValue(context, MemberNames.TypeOfReqirement.toString(), typeofreqirement.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeOfReqirement.toString(), null);
	}

	/**
	 * Set value of Project_Type
	 * @param project_type
	 */
	public final ccgprojecttracking.proxies.PT getProject_Type()
	{
		return getProject_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Type
	 */
	public final ccgprojecttracking.proxies.PT getProject_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Project_Type.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.PT.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Project_Type
	 * @param project_type
	 */
	public final void setProject_Type(ccgprojecttracking.proxies.PT project_type)
	{
		setProject_Type(getContext(), project_type);
	}

	/**
	 * Set value of Project_Type
	 * @param context
	 * @param project_type
	 */
	public final void setProject_Type(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.PT project_type)
	{
		if (project_type != null)
			getMendixObject().setValue(context, MemberNames.Project_Type.toString(), project_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.Project_Type.toString(), null);
	}

	/**
	 * @return value of Project_Created_Date
	 */
	public final java.util.Date getProject_Created_Date()
	{
		return getProject_Created_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Created_Date
	 */
	public final java.util.Date getProject_Created_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Created_Date.toString());
	}

	/**
	 * Set value of Project_Created_Date
	 * @param project_created_date
	 */
	public final void setProject_Created_Date(java.util.Date project_created_date)
	{
		setProject_Created_Date(getContext(), project_created_date);
	}

	/**
	 * Set value of Project_Created_Date
	 * @param context
	 * @param project_created_date
	 */
	public final void setProject_Created_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_created_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Created_Date.toString(), project_created_date);
	}

	/**
	 * @return value of Project_Started_Date
	 */
	public final java.util.Date getProject_Started_Date()
	{
		return getProject_Started_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Started_Date
	 */
	public final java.util.Date getProject_Started_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Started_Date.toString());
	}

	/**
	 * Set value of Project_Started_Date
	 * @param project_started_date
	 */
	public final void setProject_Started_Date(java.util.Date project_started_date)
	{
		setProject_Started_Date(getContext(), project_started_date);
	}

	/**
	 * Set value of Project_Started_Date
	 * @param context
	 * @param project_started_date
	 */
	public final void setProject_Started_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_started_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Started_Date.toString(), project_started_date);
	}

	/**
	 * @return value of Project_Published_Date
	 */
	public final java.util.Date getProject_Published_Date()
	{
		return getProject_Published_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Published_Date
	 */
	public final java.util.Date getProject_Published_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Published_Date.toString());
	}

	/**
	 * Set value of Project_Published_Date
	 * @param project_published_date
	 */
	public final void setProject_Published_Date(java.util.Date project_published_date)
	{
		setProject_Published_Date(getContext(), project_published_date);
	}

	/**
	 * Set value of Project_Published_Date
	 * @param context
	 * @param project_published_date
	 */
	public final void setProject_Published_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_published_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Published_Date.toString(), project_published_date);
	}

	/**
	 * @return value of ETA_Date
	 */
	public final java.util.Date getETA_Date()
	{
		return getETA_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of ETA_Date
	 */
	public final java.util.Date getETA_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ETA_Date.toString());
	}

	/**
	 * Set value of ETA_Date
	 * @param eta_date
	 */
	public final void setETA_Date(java.util.Date eta_date)
	{
		setETA_Date(getContext(), eta_date);
	}

	/**
	 * Set value of ETA_Date
	 * @param context
	 * @param eta_date
	 */
	public final void setETA_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date eta_date)
	{
		getMendixObject().setValue(context, MemberNames.ETA_Date.toString(), eta_date);
	}

	/**
	 * @return value of Project_End_Date
	 */
	public final java.util.Date getProject_End_Date()
	{
		return getProject_End_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_End_Date
	 */
	public final java.util.Date getProject_End_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_End_Date.toString());
	}

	/**
	 * Set value of Project_End_Date
	 * @param project_end_date
	 */
	public final void setProject_End_Date(java.util.Date project_end_date)
	{
		setProject_End_Date(getContext(), project_end_date);
	}

	/**
	 * Set value of Project_End_Date
	 * @param context
	 * @param project_end_date
	 */
	public final void setProject_End_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_end_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_End_Date.toString(), project_end_date);
	}

	/**
	 * @return value of Project_CreatedBy
	 */
	public final java.lang.String getProject_CreatedBy()
	{
		return getProject_CreatedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_CreatedBy
	 */
	public final java.lang.String getProject_CreatedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_CreatedBy.toString());
	}

	/**
	 * Set value of Project_CreatedBy
	 * @param project_createdby
	 */
	public final void setProject_CreatedBy(java.lang.String project_createdby)
	{
		setProject_CreatedBy(getContext(), project_createdby);
	}

	/**
	 * Set value of Project_CreatedBy
	 * @param context
	 * @param project_createdby
	 */
	public final void setProject_CreatedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_createdby)
	{
		getMendixObject().setValue(context, MemberNames.Project_CreatedBy.toString(), project_createdby);
	}

	/**
	 * @return value of Project_Modified_Date
	 */
	public final java.util.Date getProject_Modified_Date()
	{
		return getProject_Modified_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Modified_Date
	 */
	public final java.util.Date getProject_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Modified_Date.toString());
	}

	/**
	 * Set value of Project_Modified_Date
	 * @param project_modified_date
	 */
	public final void setProject_Modified_Date(java.util.Date project_modified_date)
	{
		setProject_Modified_Date(getContext(), project_modified_date);
	}

	/**
	 * Set value of Project_Modified_Date
	 * @param context
	 * @param project_modified_date
	 */
	public final void setProject_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_modified_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Modified_Date.toString(), project_modified_date);
	}

	/**
	 * @return value of Project_ModifiedBy
	 */
	public final java.lang.String getProject_ModifiedBy()
	{
		return getProject_ModifiedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_ModifiedBy
	 */
	public final java.lang.String getProject_ModifiedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_ModifiedBy.toString());
	}

	/**
	 * Set value of Project_ModifiedBy
	 * @param project_modifiedby
	 */
	public final void setProject_ModifiedBy(java.lang.String project_modifiedby)
	{
		setProject_ModifiedBy(getContext(), project_modifiedby);
	}

	/**
	 * Set value of Project_ModifiedBy
	 * @param context
	 * @param project_modifiedby
	 */
	public final void setProject_ModifiedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_modifiedby)
	{
		getMendixObject().setValue(context, MemberNames.Project_ModifiedBy.toString(), project_modifiedby);
	}

	/**
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id()
	{
		return getESR_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ESR_Id.toString());
	}

	/**
	 * Set value of ESR_Id
	 * @param esr_id
	 */
	public final void setESR_Id(java.lang.String esr_id)
	{
		setESR_Id(getContext(), esr_id);
	}

	/**
	 * Set value of ESR_Id
	 * @param context
	 * @param esr_id
	 */
	public final void setESR_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String esr_id)
	{
		getMendixObject().setValue(context, MemberNames.ESR_Id.toString(), esr_id);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase()
	{
		return getCurrent_Phase(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Current_Phase.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Currentphase.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final void setCurrent_Phase(ccgprojecttracking.proxies.Currentphase current_phase)
	{
		setCurrent_Phase(getContext(), current_phase);
	}

	/**
	 * Set value of Current_Phase
	 * @param context
	 * @param current_phase
	 */
	public final void setCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Currentphase current_phase)
	{
		if (current_phase != null)
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), current_phase.toString());
		else
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), null);
	}

	/**
	 * Set value of Project_status
	 * @param project_status
	 */
	public final ccgprojecttracking.proxies.PS getProject_status()
	{
		return getProject_status(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_status
	 */
	public final ccgprojecttracking.proxies.PS getProject_status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Project_status.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.PS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Project_status
	 * @param project_status
	 */
	public final void setProject_status(ccgprojecttracking.proxies.PS project_status)
	{
		setProject_status(getContext(), project_status);
	}

	/**
	 * Set value of Project_status
	 * @param context
	 * @param project_status
	 */
	public final void setProject_status(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.PS project_status)
	{
		if (project_status != null)
			getMendixObject().setValue(context, MemberNames.Project_status.toString(), project_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Project_status.toString(), null);
	}

	/**
	 * @return value of Latest_Published_Date
	 */
	public final java.util.Date getLatest_Published_Date()
	{
		return getLatest_Published_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Latest_Published_Date
	 */
	public final java.util.Date getLatest_Published_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Latest_Published_Date.toString());
	}

	/**
	 * Set value of Latest_Published_Date
	 * @param latest_published_date
	 */
	public final void setLatest_Published_Date(java.util.Date latest_published_date)
	{
		setLatest_Published_Date(getContext(), latest_published_date);
	}

	/**
	 * Set value of Latest_Published_Date
	 * @param context
	 * @param latest_published_date
	 */
	public final void setLatest_Published_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date latest_published_date)
	{
		getMendixObject().setValue(context, MemberNames.Latest_Published_Date.toString(), latest_published_date);
	}

	/**
	 * @return value of SME
	 */
	public final java.lang.String getSME()
	{
		return getSME(getContext());
	}

	/**
	 * @param context
	 * @return value of SME
	 */
	public final java.lang.String getSME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SME.toString());
	}

	/**
	 * Set value of SME
	 * @param sme
	 */
	public final void setSME(java.lang.String sme)
	{
		setSME(getContext(), sme);
	}

	/**
	 * Set value of SME
	 * @param context
	 * @param sme
	 */
	public final void setSME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sme)
	{
		getMendixObject().setValue(context, MemberNames.SME.toString(), sme);
	}

	/**
	 * @return value of Project_Owner
	 */
	public final java.lang.String getProject_Owner()
	{
		return getProject_Owner(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Owner
	 */
	public final java.lang.String getProject_Owner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_Owner.toString());
	}

	/**
	 * Set value of Project_Owner
	 * @param project_owner
	 */
	public final void setProject_Owner(java.lang.String project_owner)
	{
		setProject_Owner(getContext(), project_owner);
	}

	/**
	 * Set value of Project_Owner
	 * @param context
	 * @param project_owner
	 */
	public final void setProject_Owner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_owner)
	{
		getMendixObject().setValue(context, MemberNames.Project_Owner.toString(), project_owner);
	}

	/**
	 * @return value of Enhancement_Task
	 */
	public final ccgprojecttracking.proxies.Task getEnhancement_Task() throws com.mendix.core.CoreException
	{
		return getEnhancement_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of Enhancement_Task
	 */
	public final ccgprojecttracking.proxies.Task getEnhancement_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Enhancement_Task.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Task.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Enhancement_Task
	 * @param enhancement_task
	 */
	public final void setEnhancement_Task(ccgprojecttracking.proxies.Task enhancement_task)
	{
		setEnhancement_Task(getContext(), enhancement_task);
	}

	/**
	 * Set value of Enhancement_Task
	 * @param context
	 * @param enhancement_task
	 */
	public final void setEnhancement_Task(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Task enhancement_task)
	{
		if (enhancement_task == null)
			getMendixObject().setValue(context, MemberNames.Enhancement_Task.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Enhancement_Task.toString(), enhancement_task.getMendixObject().getId());
	}

	/**
	 * @return value of Enhancement_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getEnhancement_ProjectDetails() throws com.mendix.core.CoreException
	{
		return getEnhancement_ProjectDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Enhancement_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getEnhancement_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Enhancement_ProjectDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Enhancement_ProjectDetails
	 * @param enhancement_projectdetails
	 */
	public final void setEnhancement_ProjectDetails(ccgprojecttracking.proxies.ProjectDetails enhancement_projectdetails)
	{
		setEnhancement_ProjectDetails(getContext(), enhancement_projectdetails);
	}

	/**
	 * Set value of Enhancement_ProjectDetails
	 * @param context
	 * @param enhancement_projectdetails
	 */
	public final void setEnhancement_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectDetails enhancement_projectdetails)
	{
		if (enhancement_projectdetails == null)
			getMendixObject().setValue(context, MemberNames.Enhancement_ProjectDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Enhancement_ProjectDetails.toString(), enhancement_projectdetails.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return enhancementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.Enhancement that = (ccgprojecttracking.proxies.Enhancement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.Enhancement";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
