// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class EventDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eventDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.EventDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Event_ID("Event_ID"),
		Last_Modified_Date("Last_Modified_Date"),
		Cus_ReqVisualCount("Cus_ReqVisualCount"),
		CompletedVisualsCount("CompletedVisualsCount"),
		Responsible_Dev("Responsible_Dev"),
		Requirement_List("Requirement_List"),
		Requirement_DES("Requirement_DES"),
		Current_Status("Current_Status"),
		Event_EndDate("Event_EndDate"),
		Estimated_Complete_Date("Estimated_Complete_Date"),
		Event_Roadblock("Event_Roadblock"),
		Roadblock_DES("Roadblock_DES"),
		Point_Of_Contact("Point_Of_Contact"),
		RoadBlock_Status("RoadBlock_Status"),
		Comments("Comments"),
		EventDetails_Task("CCGProjectTracking.EventDetails_Task"),
		EventDetails_ProjectDetails("CCGProjectTracking.EventDetails_ProjectDetails"),
		EventDetails_Employee("CCGProjectTracking.EventDetails_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EventDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.EventDetails"));
	}

	protected EventDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eventDetailsMendixObject)
	{
		if (eventDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.EventDetails", eventDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.EventDetails");

		this.eventDetailsMendixObject = eventDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EventDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.EventDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.EventDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.EventDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.EventDetails(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.EventDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.EventDetails.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.EventDetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.EventDetails> result = new java.util.ArrayList<ccgprojecttracking.proxies.EventDetails>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.EventDetails" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.EventDetails.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Event_ID
	 */
	public final java.lang.Long getEvent_ID()
	{
		return getEvent_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_ID
	 */
	public final java.lang.Long getEvent_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Event_ID.toString());
	}

	/**
	 * Set value of Event_ID
	 * @param event_id
	 */
	public final void setEvent_ID(java.lang.Long event_id)
	{
		setEvent_ID(getContext(), event_id);
	}

	/**
	 * Set value of Event_ID
	 * @param context
	 * @param event_id
	 */
	public final void setEvent_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long event_id)
	{
		getMendixObject().setValue(context, MemberNames.Event_ID.toString(), event_id);
	}

	/**
	 * @return value of Last_Modified_Date
	 */
	public final java.util.Date getLast_Modified_Date()
	{
		return getLast_Modified_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Last_Modified_Date
	 */
	public final java.util.Date getLast_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Last_Modified_Date.toString());
	}

	/**
	 * Set value of Last_Modified_Date
	 * @param last_modified_date
	 */
	public final void setLast_Modified_Date(java.util.Date last_modified_date)
	{
		setLast_Modified_Date(getContext(), last_modified_date);
	}

	/**
	 * Set value of Last_Modified_Date
	 * @param context
	 * @param last_modified_date
	 */
	public final void setLast_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date last_modified_date)
	{
		getMendixObject().setValue(context, MemberNames.Last_Modified_Date.toString(), last_modified_date);
	}

	/**
	 * @return value of Cus_ReqVisualCount
	 */
	public final java.lang.Integer getCus_ReqVisualCount()
	{
		return getCus_ReqVisualCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Cus_ReqVisualCount
	 */
	public final java.lang.Integer getCus_ReqVisualCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cus_ReqVisualCount.toString());
	}

	/**
	 * Set value of Cus_ReqVisualCount
	 * @param cus_reqvisualcount
	 */
	public final void setCus_ReqVisualCount(java.lang.Integer cus_reqvisualcount)
	{
		setCus_ReqVisualCount(getContext(), cus_reqvisualcount);
	}

	/**
	 * Set value of Cus_ReqVisualCount
	 * @param context
	 * @param cus_reqvisualcount
	 */
	public final void setCus_ReqVisualCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cus_reqvisualcount)
	{
		getMendixObject().setValue(context, MemberNames.Cus_ReqVisualCount.toString(), cus_reqvisualcount);
	}

	/**
	 * @return value of CompletedVisualsCount
	 */
	public final java.lang.Integer getCompletedVisualsCount()
	{
		return getCompletedVisualsCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedVisualsCount
	 */
	public final java.lang.Integer getCompletedVisualsCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CompletedVisualsCount.toString());
	}

	/**
	 * Set value of CompletedVisualsCount
	 * @param completedvisualscount
	 */
	public final void setCompletedVisualsCount(java.lang.Integer completedvisualscount)
	{
		setCompletedVisualsCount(getContext(), completedvisualscount);
	}

	/**
	 * Set value of CompletedVisualsCount
	 * @param context
	 * @param completedvisualscount
	 */
	public final void setCompletedVisualsCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer completedvisualscount)
	{
		getMendixObject().setValue(context, MemberNames.CompletedVisualsCount.toString(), completedvisualscount);
	}

	/**
	 * @return value of Responsible_Dev
	 */
	public final java.lang.String getResponsible_Dev()
	{
		return getResponsible_Dev(getContext());
	}

	/**
	 * @param context
	 * @return value of Responsible_Dev
	 */
	public final java.lang.String getResponsible_Dev(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Responsible_Dev.toString());
	}

	/**
	 * Set value of Responsible_Dev
	 * @param responsible_dev
	 */
	public final void setResponsible_Dev(java.lang.String responsible_dev)
	{
		setResponsible_Dev(getContext(), responsible_dev);
	}

	/**
	 * Set value of Responsible_Dev
	 * @param context
	 * @param responsible_dev
	 */
	public final void setResponsible_Dev(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String responsible_dev)
	{
		getMendixObject().setValue(context, MemberNames.Responsible_Dev.toString(), responsible_dev);
	}

	/**
	 * @return value of Requirement_List
	 */
	public final java.lang.String getRequirement_List()
	{
		return getRequirement_List(getContext());
	}

	/**
	 * @param context
	 * @return value of Requirement_List
	 */
	public final java.lang.String getRequirement_List(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Requirement_List.toString());
	}

	/**
	 * Set value of Requirement_List
	 * @param requirement_list
	 */
	public final void setRequirement_List(java.lang.String requirement_list)
	{
		setRequirement_List(getContext(), requirement_list);
	}

	/**
	 * Set value of Requirement_List
	 * @param context
	 * @param requirement_list
	 */
	public final void setRequirement_List(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requirement_list)
	{
		getMendixObject().setValue(context, MemberNames.Requirement_List.toString(), requirement_list);
	}

	/**
	 * @return value of Requirement_DES
	 */
	public final java.lang.String getRequirement_DES()
	{
		return getRequirement_DES(getContext());
	}

	/**
	 * @param context
	 * @return value of Requirement_DES
	 */
	public final java.lang.String getRequirement_DES(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Requirement_DES.toString());
	}

	/**
	 * Set value of Requirement_DES
	 * @param requirement_des
	 */
	public final void setRequirement_DES(java.lang.String requirement_des)
	{
		setRequirement_DES(getContext(), requirement_des);
	}

	/**
	 * Set value of Requirement_DES
	 * @param context
	 * @param requirement_des
	 */
	public final void setRequirement_DES(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requirement_des)
	{
		getMendixObject().setValue(context, MemberNames.Requirement_DES.toString(), requirement_des);
	}

	/**
	 * Set value of Current_Status
	 * @param current_status
	 */
	public final ccgprojecttracking.proxies.Event_Status getCurrent_Status()
	{
		return getCurrent_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Status
	 */
	public final ccgprojecttracking.proxies.Event_Status getCurrent_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Current_Status.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Event_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Current_Status
	 * @param current_status
	 */
	public final void setCurrent_Status(ccgprojecttracking.proxies.Event_Status current_status)
	{
		setCurrent_Status(getContext(), current_status);
	}

	/**
	 * Set value of Current_Status
	 * @param context
	 * @param current_status
	 */
	public final void setCurrent_Status(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Event_Status current_status)
	{
		if (current_status != null)
			getMendixObject().setValue(context, MemberNames.Current_Status.toString(), current_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Current_Status.toString(), null);
	}

	/**
	 * @return value of Event_EndDate
	 */
	public final java.util.Date getEvent_EndDate()
	{
		return getEvent_EndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_EndDate
	 */
	public final java.util.Date getEvent_EndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Event_EndDate.toString());
	}

	/**
	 * Set value of Event_EndDate
	 * @param event_enddate
	 */
	public final void setEvent_EndDate(java.util.Date event_enddate)
	{
		setEvent_EndDate(getContext(), event_enddate);
	}

	/**
	 * Set value of Event_EndDate
	 * @param context
	 * @param event_enddate
	 */
	public final void setEvent_EndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date event_enddate)
	{
		getMendixObject().setValue(context, MemberNames.Event_EndDate.toString(), event_enddate);
	}

	/**
	 * @return value of Estimated_Complete_Date
	 */
	public final java.util.Date getEstimated_Complete_Date()
	{
		return getEstimated_Complete_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Estimated_Complete_Date
	 */
	public final java.util.Date getEstimated_Complete_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Estimated_Complete_Date.toString());
	}

	/**
	 * Set value of Estimated_Complete_Date
	 * @param estimated_complete_date
	 */
	public final void setEstimated_Complete_Date(java.util.Date estimated_complete_date)
	{
		setEstimated_Complete_Date(getContext(), estimated_complete_date);
	}

	/**
	 * Set value of Estimated_Complete_Date
	 * @param context
	 * @param estimated_complete_date
	 */
	public final void setEstimated_Complete_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date estimated_complete_date)
	{
		getMendixObject().setValue(context, MemberNames.Estimated_Complete_Date.toString(), estimated_complete_date);
	}

	/**
	 * Set value of Event_Roadblock
	 * @param event_roadblock
	 */
	public final ccgprojecttracking.proxies.Eve_Roadblock getEvent_Roadblock()
	{
		return getEvent_Roadblock(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_Roadblock
	 */
	public final ccgprojecttracking.proxies.Eve_Roadblock getEvent_Roadblock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Event_Roadblock.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Eve_Roadblock.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Event_Roadblock
	 * @param event_roadblock
	 */
	public final void setEvent_Roadblock(ccgprojecttracking.proxies.Eve_Roadblock event_roadblock)
	{
		setEvent_Roadblock(getContext(), event_roadblock);
	}

	/**
	 * Set value of Event_Roadblock
	 * @param context
	 * @param event_roadblock
	 */
	public final void setEvent_Roadblock(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Eve_Roadblock event_roadblock)
	{
		if (event_roadblock != null)
			getMendixObject().setValue(context, MemberNames.Event_Roadblock.toString(), event_roadblock.toString());
		else
			getMendixObject().setValue(context, MemberNames.Event_Roadblock.toString(), null);
	}

	/**
	 * @return value of Roadblock_DES
	 */
	public final java.lang.String getRoadblock_DES()
	{
		return getRoadblock_DES(getContext());
	}

	/**
	 * @param context
	 * @return value of Roadblock_DES
	 */
	public final java.lang.String getRoadblock_DES(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Roadblock_DES.toString());
	}

	/**
	 * Set value of Roadblock_DES
	 * @param roadblock_des
	 */
	public final void setRoadblock_DES(java.lang.String roadblock_des)
	{
		setRoadblock_DES(getContext(), roadblock_des);
	}

	/**
	 * Set value of Roadblock_DES
	 * @param context
	 * @param roadblock_des
	 */
	public final void setRoadblock_DES(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roadblock_des)
	{
		getMendixObject().setValue(context, MemberNames.Roadblock_DES.toString(), roadblock_des);
	}

	/**
	 * @return value of Point_Of_Contact
	 */
	public final java.lang.String getPoint_Of_Contact()
	{
		return getPoint_Of_Contact(getContext());
	}

	/**
	 * @param context
	 * @return value of Point_Of_Contact
	 */
	public final java.lang.String getPoint_Of_Contact(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Point_Of_Contact.toString());
	}

	/**
	 * Set value of Point_Of_Contact
	 * @param point_of_contact
	 */
	public final void setPoint_Of_Contact(java.lang.String point_of_contact)
	{
		setPoint_Of_Contact(getContext(), point_of_contact);
	}

	/**
	 * Set value of Point_Of_Contact
	 * @param context
	 * @param point_of_contact
	 */
	public final void setPoint_Of_Contact(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String point_of_contact)
	{
		getMendixObject().setValue(context, MemberNames.Point_Of_Contact.toString(), point_of_contact);
	}

	/**
	 * Set value of RoadBlock_Status
	 * @param roadblock_status
	 */
	public final ccgprojecttracking.proxies.Roadblock getRoadBlock_Status()
	{
		return getRoadBlock_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of RoadBlock_Status
	 */
	public final ccgprojecttracking.proxies.Roadblock getRoadBlock_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RoadBlock_Status.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Roadblock.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RoadBlock_Status
	 * @param roadblock_status
	 */
	public final void setRoadBlock_Status(ccgprojecttracking.proxies.Roadblock roadblock_status)
	{
		setRoadBlock_Status(getContext(), roadblock_status);
	}

	/**
	 * Set value of RoadBlock_Status
	 * @param context
	 * @param roadblock_status
	 */
	public final void setRoadBlock_Status(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Roadblock roadblock_status)
	{
		if (roadblock_status != null)
			getMendixObject().setValue(context, MemberNames.RoadBlock_Status.toString(), roadblock_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.RoadBlock_Status.toString(), null);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @return value of EventDetails_Task
	 */
	public final ccgprojecttracking.proxies.Task getEventDetails_Task() throws com.mendix.core.CoreException
	{
		return getEventDetails_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of EventDetails_Task
	 */
	public final ccgprojecttracking.proxies.Task getEventDetails_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EventDetails_Task.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Task.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EventDetails_Task
	 * @param eventdetails_task
	 */
	public final void setEventDetails_Task(ccgprojecttracking.proxies.Task eventdetails_task)
	{
		setEventDetails_Task(getContext(), eventdetails_task);
	}

	/**
	 * Set value of EventDetails_Task
	 * @param context
	 * @param eventdetails_task
	 */
	public final void setEventDetails_Task(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Task eventdetails_task)
	{
		if (eventdetails_task == null)
			getMendixObject().setValue(context, MemberNames.EventDetails_Task.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EventDetails_Task.toString(), eventdetails_task.getMendixObject().getId());
	}

	/**
	 * @return value of EventDetails_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getEventDetails_ProjectDetails() throws com.mendix.core.CoreException
	{
		return getEventDetails_ProjectDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of EventDetails_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getEventDetails_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EventDetails_ProjectDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EventDetails_ProjectDetails
	 * @param eventdetails_projectdetails
	 */
	public final void setEventDetails_ProjectDetails(ccgprojecttracking.proxies.ProjectDetails eventdetails_projectdetails)
	{
		setEventDetails_ProjectDetails(getContext(), eventdetails_projectdetails);
	}

	/**
	 * Set value of EventDetails_ProjectDetails
	 * @param context
	 * @param eventdetails_projectdetails
	 */
	public final void setEventDetails_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectDetails eventdetails_projectdetails)
	{
		if (eventdetails_projectdetails == null)
			getMendixObject().setValue(context, MemberNames.EventDetails_ProjectDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EventDetails_ProjectDetails.toString(), eventdetails_projectdetails.getMendixObject().getId());
	}

	/**
	 * @return value of EventDetails_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getEventDetails_Employee() throws com.mendix.core.CoreException
	{
		return getEventDetails_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of EventDetails_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getEventDetails_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EventDetails_Employee.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EventDetails_Employee
	 * @param eventdetails_employee
	 */
	public final void setEventDetails_Employee(ccgprojecttracking.proxies.Employee eventdetails_employee)
	{
		setEventDetails_Employee(getContext(), eventdetails_employee);
	}

	/**
	 * Set value of EventDetails_Employee
	 * @param context
	 * @param eventdetails_employee
	 */
	public final void setEventDetails_Employee(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee eventdetails_employee)
	{
		if (eventdetails_employee == null)
			getMendixObject().setValue(context, MemberNames.EventDetails_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EventDetails_Employee.toString(), eventdetails_employee.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eventDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.EventDetails that = (ccgprojecttracking.proxies.EventDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.EventDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
