// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class ProjectDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject projectDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.ProjectDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProjectDescription("ProjectDescription"),
		TypeOfReqirement("TypeOfReqirement"),
		Project_Type("Project_Type"),
		Project_Created_Date("Project_Created_Date"),
		Project_Started_Date("Project_Started_Date"),
		Project_Published_Date("Project_Published_Date"),
		Project_status("Project_status"),
		Latest_Published_Date("Latest_Published_Date"),
		ETA_Date("ETA_Date"),
		Project_End_Date("Project_End_Date"),
		Project_CreatedBy("Project_CreatedBy"),
		Project_Modified_Date("Project_Modified_Date"),
		Prj_ID("Prj_ID"),
		Project_ModifiedBy("Project_ModifiedBy"),
		ESR_Id("ESR_Id"),
		Current_Phase("Current_Phase"),
		Project_Name("Project_Name"),
		ProjectDetails_EventDetails("CCGProjectTracking.ProjectDetails_EventDetails"),
		ProjectDetails_ProjectDept("CCGProjectTracking.ProjectDetails_ProjectDept"),
		ProjectDetails_Task("CCGProjectTracking.ProjectDetails_Task"),
		ProjectDetails_Employee("CCGProjectTracking.ProjectDetails_Employee"),
		ProjectDetails_ProjectOwner("CCGProjectTracking.ProjectDetails_ProjectOwner"),
		ProjectDetails_SME("CCGProjectTracking.ProjectDetails_SME"),
		ProjectDetails_Modified("CCGProjectTracking.ProjectDetails_Modified"),
		ProjectDetails_Enhancement("CCGProjectTracking.ProjectDetails_Enhancement"),
		ProjectDetails_Revision("CCGProjectTracking.ProjectDetails_Revision"),
		ProjectDetails_Sprint("CCGProjectTracking.ProjectDetails_Sprint"),
		ProjectDetails_DataArchitect("CCGProjectTracking.ProjectDetails_DataArchitect"),
		ProjectDetails_BusinessCoordinator("CCGProjectTracking.ProjectDetails_BusinessCoordinator"),
		ProjectDetails_BusinessCo("CCGProjectTracking.ProjectDetails_BusinessCo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.ProjectDetails"));
	}

	protected ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject projectDetailsMendixObject)
	{
		if (projectDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.ProjectDetails", projectDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.ProjectDetails");

		this.projectDetailsMendixObject = projectDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProjectDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.ProjectDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.ProjectDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.ProjectDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.ProjectDetails(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.ProjectDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.ProjectDetails.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.ProjectDetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.ProjectDetails> result = new java.util.ArrayList<ccgprojecttracking.proxies.ProjectDetails>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.ProjectDetails" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.ProjectDetails.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProjectDescription
	 */
	public final java.lang.String getProjectDescription()
	{
		return getProjectDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDescription
	 */
	public final java.lang.String getProjectDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectDescription.toString());
	}

	/**
	 * Set value of ProjectDescription
	 * @param projectdescription
	 */
	public final void setProjectDescription(java.lang.String projectdescription)
	{
		setProjectDescription(getContext(), projectdescription);
	}

	/**
	 * Set value of ProjectDescription
	 * @param context
	 * @param projectdescription
	 */
	public final void setProjectDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectdescription)
	{
		getMendixObject().setValue(context, MemberNames.ProjectDescription.toString(), projectdescription);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param typeofreqirement
	 */
	public final ccgprojecttracking.proxies.TYR getTypeOfReqirement()
	{
		return getTypeOfReqirement(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeOfReqirement
	 */
	public final ccgprojecttracking.proxies.TYR getTypeOfReqirement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeOfReqirement.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.TYR.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param typeofreqirement
	 */
	public final void setTypeOfReqirement(ccgprojecttracking.proxies.TYR typeofreqirement)
	{
		setTypeOfReqirement(getContext(), typeofreqirement);
	}

	/**
	 * Set value of TypeOfReqirement
	 * @param context
	 * @param typeofreqirement
	 */
	public final void setTypeOfReqirement(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.TYR typeofreqirement)
	{
		if (typeofreqirement != null)
			getMendixObject().setValue(context, MemberNames.TypeOfReqirement.toString(), typeofreqirement.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeOfReqirement.toString(), null);
	}

	/**
	 * Set value of Project_Type
	 * @param project_type
	 */
	public final ccgprojecttracking.proxies.PT getProject_Type()
	{
		return getProject_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Type
	 */
	public final ccgprojecttracking.proxies.PT getProject_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Project_Type.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.PT.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Project_Type
	 * @param project_type
	 */
	public final void setProject_Type(ccgprojecttracking.proxies.PT project_type)
	{
		setProject_Type(getContext(), project_type);
	}

	/**
	 * Set value of Project_Type
	 * @param context
	 * @param project_type
	 */
	public final void setProject_Type(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.PT project_type)
	{
		if (project_type != null)
			getMendixObject().setValue(context, MemberNames.Project_Type.toString(), project_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.Project_Type.toString(), null);
	}

	/**
	 * @return value of Project_Created_Date
	 */
	public final java.util.Date getProject_Created_Date()
	{
		return getProject_Created_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Created_Date
	 */
	public final java.util.Date getProject_Created_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Created_Date.toString());
	}

	/**
	 * Set value of Project_Created_Date
	 * @param project_created_date
	 */
	public final void setProject_Created_Date(java.util.Date project_created_date)
	{
		setProject_Created_Date(getContext(), project_created_date);
	}

	/**
	 * Set value of Project_Created_Date
	 * @param context
	 * @param project_created_date
	 */
	public final void setProject_Created_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_created_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Created_Date.toString(), project_created_date);
	}

	/**
	 * @return value of Project_Started_Date
	 */
	public final java.util.Date getProject_Started_Date()
	{
		return getProject_Started_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Started_Date
	 */
	public final java.util.Date getProject_Started_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Started_Date.toString());
	}

	/**
	 * Set value of Project_Started_Date
	 * @param project_started_date
	 */
	public final void setProject_Started_Date(java.util.Date project_started_date)
	{
		setProject_Started_Date(getContext(), project_started_date);
	}

	/**
	 * Set value of Project_Started_Date
	 * @param context
	 * @param project_started_date
	 */
	public final void setProject_Started_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_started_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Started_Date.toString(), project_started_date);
	}

	/**
	 * @return value of Project_Published_Date
	 */
	public final java.util.Date getProject_Published_Date()
	{
		return getProject_Published_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Published_Date
	 */
	public final java.util.Date getProject_Published_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Published_Date.toString());
	}

	/**
	 * Set value of Project_Published_Date
	 * @param project_published_date
	 */
	public final void setProject_Published_Date(java.util.Date project_published_date)
	{
		setProject_Published_Date(getContext(), project_published_date);
	}

	/**
	 * Set value of Project_Published_Date
	 * @param context
	 * @param project_published_date
	 */
	public final void setProject_Published_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_published_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Published_Date.toString(), project_published_date);
	}

	/**
	 * Set value of Project_status
	 * @param project_status
	 */
	public final ccgprojecttracking.proxies.PS getProject_status()
	{
		return getProject_status(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_status
	 */
	public final ccgprojecttracking.proxies.PS getProject_status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Project_status.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.PS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Project_status
	 * @param project_status
	 */
	public final void setProject_status(ccgprojecttracking.proxies.PS project_status)
	{
		setProject_status(getContext(), project_status);
	}

	/**
	 * Set value of Project_status
	 * @param context
	 * @param project_status
	 */
	public final void setProject_status(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.PS project_status)
	{
		if (project_status != null)
			getMendixObject().setValue(context, MemberNames.Project_status.toString(), project_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Project_status.toString(), null);
	}

	/**
	 * @return value of Latest_Published_Date
	 */
	public final java.util.Date getLatest_Published_Date()
	{
		return getLatest_Published_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Latest_Published_Date
	 */
	public final java.util.Date getLatest_Published_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Latest_Published_Date.toString());
	}

	/**
	 * Set value of Latest_Published_Date
	 * @param latest_published_date
	 */
	public final void setLatest_Published_Date(java.util.Date latest_published_date)
	{
		setLatest_Published_Date(getContext(), latest_published_date);
	}

	/**
	 * Set value of Latest_Published_Date
	 * @param context
	 * @param latest_published_date
	 */
	public final void setLatest_Published_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date latest_published_date)
	{
		getMendixObject().setValue(context, MemberNames.Latest_Published_Date.toString(), latest_published_date);
	}

	/**
	 * @return value of ETA_Date
	 */
	public final java.util.Date getETA_Date()
	{
		return getETA_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of ETA_Date
	 */
	public final java.util.Date getETA_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ETA_Date.toString());
	}

	/**
	 * Set value of ETA_Date
	 * @param eta_date
	 */
	public final void setETA_Date(java.util.Date eta_date)
	{
		setETA_Date(getContext(), eta_date);
	}

	/**
	 * Set value of ETA_Date
	 * @param context
	 * @param eta_date
	 */
	public final void setETA_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date eta_date)
	{
		getMendixObject().setValue(context, MemberNames.ETA_Date.toString(), eta_date);
	}

	/**
	 * @return value of Project_End_Date
	 */
	public final java.util.Date getProject_End_Date()
	{
		return getProject_End_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_End_Date
	 */
	public final java.util.Date getProject_End_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_End_Date.toString());
	}

	/**
	 * Set value of Project_End_Date
	 * @param project_end_date
	 */
	public final void setProject_End_Date(java.util.Date project_end_date)
	{
		setProject_End_Date(getContext(), project_end_date);
	}

	/**
	 * Set value of Project_End_Date
	 * @param context
	 * @param project_end_date
	 */
	public final void setProject_End_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_end_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_End_Date.toString(), project_end_date);
	}

	/**
	 * @return value of Project_CreatedBy
	 */
	public final java.lang.String getProject_CreatedBy()
	{
		return getProject_CreatedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_CreatedBy
	 */
	public final java.lang.String getProject_CreatedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_CreatedBy.toString());
	}

	/**
	 * Set value of Project_CreatedBy
	 * @param project_createdby
	 */
	public final void setProject_CreatedBy(java.lang.String project_createdby)
	{
		setProject_CreatedBy(getContext(), project_createdby);
	}

	/**
	 * Set value of Project_CreatedBy
	 * @param context
	 * @param project_createdby
	 */
	public final void setProject_CreatedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_createdby)
	{
		getMendixObject().setValue(context, MemberNames.Project_CreatedBy.toString(), project_createdby);
	}

	/**
	 * @return value of Project_Modified_Date
	 */
	public final java.util.Date getProject_Modified_Date()
	{
		return getProject_Modified_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Modified_Date
	 */
	public final java.util.Date getProject_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Project_Modified_Date.toString());
	}

	/**
	 * Set value of Project_Modified_Date
	 * @param project_modified_date
	 */
	public final void setProject_Modified_Date(java.util.Date project_modified_date)
	{
		setProject_Modified_Date(getContext(), project_modified_date);
	}

	/**
	 * Set value of Project_Modified_Date
	 * @param context
	 * @param project_modified_date
	 */
	public final void setProject_Modified_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date project_modified_date)
	{
		getMendixObject().setValue(context, MemberNames.Project_Modified_Date.toString(), project_modified_date);
	}

	/**
	 * @return value of Prj_ID
	 */
	public final java.lang.String getPrj_ID()
	{
		return getPrj_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Prj_ID
	 */
	public final java.lang.String getPrj_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Prj_ID.toString());
	}

	/**
	 * Set value of Prj_ID
	 * @param prj_id
	 */
	public final void setPrj_ID(java.lang.String prj_id)
	{
		setPrj_ID(getContext(), prj_id);
	}

	/**
	 * Set value of Prj_ID
	 * @param context
	 * @param prj_id
	 */
	public final void setPrj_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prj_id)
	{
		getMendixObject().setValue(context, MemberNames.Prj_ID.toString(), prj_id);
	}

	/**
	 * @return value of Project_ModifiedBy
	 */
	public final java.lang.String getProject_ModifiedBy()
	{
		return getProject_ModifiedBy(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_ModifiedBy
	 */
	public final java.lang.String getProject_ModifiedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_ModifiedBy.toString());
	}

	/**
	 * Set value of Project_ModifiedBy
	 * @param project_modifiedby
	 */
	public final void setProject_ModifiedBy(java.lang.String project_modifiedby)
	{
		setProject_ModifiedBy(getContext(), project_modifiedby);
	}

	/**
	 * Set value of Project_ModifiedBy
	 * @param context
	 * @param project_modifiedby
	 */
	public final void setProject_ModifiedBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_modifiedby)
	{
		getMendixObject().setValue(context, MemberNames.Project_ModifiedBy.toString(), project_modifiedby);
	}

	/**
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id()
	{
		return getESR_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ESR_Id.toString());
	}

	/**
	 * Set value of ESR_Id
	 * @param esr_id
	 */
	public final void setESR_Id(java.lang.String esr_id)
	{
		setESR_Id(getContext(), esr_id);
	}

	/**
	 * Set value of ESR_Id
	 * @param context
	 * @param esr_id
	 */
	public final void setESR_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String esr_id)
	{
		getMendixObject().setValue(context, MemberNames.ESR_Id.toString(), esr_id);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase()
	{
		return getCurrent_Phase(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Current_Phase.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Currentphase.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final void setCurrent_Phase(ccgprojecttracking.proxies.Currentphase current_phase)
	{
		setCurrent_Phase(getContext(), current_phase);
	}

	/**
	 * Set value of Current_Phase
	 * @param context
	 * @param current_phase
	 */
	public final void setCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Currentphase current_phase)
	{
		if (current_phase != null)
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), current_phase.toString());
		else
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), null);
	}

	/**
	 * @return value of Project_Name
	 */
	public final java.lang.String getProject_Name()
	{
		return getProject_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Project_Name
	 */
	public final java.lang.String getProject_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Project_Name.toString());
	}

	/**
	 * Set value of Project_Name
	 * @param project_name
	 */
	public final void setProject_Name(java.lang.String project_name)
	{
		setProject_Name(getContext(), project_name);
	}

	/**
	 * Set value of Project_Name
	 * @param context
	 * @param project_name
	 */
	public final void setProject_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String project_name)
	{
		getMendixObject().setValue(context, MemberNames.Project_Name.toString(), project_name);
	}

	/**
	 * @return value of ProjectDetails_EventDetails
	 */
	public final ccgprojecttracking.proxies.EventDetails getProjectDetails_EventDetails() throws com.mendix.core.CoreException
	{
		return getProjectDetails_EventDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_EventDetails
	 */
	public final ccgprojecttracking.proxies.EventDetails getProjectDetails_EventDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.EventDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_EventDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.EventDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_EventDetails
	 * @param projectdetails_eventdetails
	 */
	public final void setProjectDetails_EventDetails(ccgprojecttracking.proxies.EventDetails projectdetails_eventdetails)
	{
		setProjectDetails_EventDetails(getContext(), projectdetails_eventdetails);
	}

	/**
	 * Set value of ProjectDetails_EventDetails
	 * @param context
	 * @param projectdetails_eventdetails
	 */
	public final void setProjectDetails_EventDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.EventDetails projectdetails_eventdetails)
	{
		if (projectdetails_eventdetails == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_EventDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_EventDetails.toString(), projectdetails_eventdetails.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_ProjectDept
	 */
	public final ccgprojecttracking.proxies.ProjectDept getProjectDetails_ProjectDept() throws com.mendix.core.CoreException
	{
		return getProjectDetails_ProjectDept(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_ProjectDept
	 */
	public final ccgprojecttracking.proxies.ProjectDept getProjectDetails_ProjectDept(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectDept result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_ProjectDept.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectDept.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_ProjectDept
	 * @param projectdetails_projectdept
	 */
	public final void setProjectDetails_ProjectDept(ccgprojecttracking.proxies.ProjectDept projectdetails_projectdept)
	{
		setProjectDetails_ProjectDept(getContext(), projectdetails_projectdept);
	}

	/**
	 * Set value of ProjectDetails_ProjectDept
	 * @param context
	 * @param projectdetails_projectdept
	 */
	public final void setProjectDetails_ProjectDept(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectDept projectdetails_projectdept)
	{
		if (projectdetails_projectdept == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_ProjectDept.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_ProjectDept.toString(), projectdetails_projectdept.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_Task
	 */
	public final ccgprojecttracking.proxies.Task getProjectDetails_Task() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Task
	 */
	public final ccgprojecttracking.proxies.Task getProjectDetails_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_Task.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Task.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_Task
	 * @param projectdetails_task
	 */
	public final void setProjectDetails_Task(ccgprojecttracking.proxies.Task projectdetails_task)
	{
		setProjectDetails_Task(getContext(), projectdetails_task);
	}

	/**
	 * Set value of ProjectDetails_Task
	 * @param context
	 * @param projectdetails_task
	 */
	public final void setProjectDetails_Task(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Task projectdetails_task)
	{
		if (projectdetails_task == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Task.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Task.toString(), projectdetails_task.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_Employee
	 */
	public final java.util.List<ccgprojecttracking.proxies.Employee> getProjectDetails_Employee() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Employee
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.Employee> getProjectDetails_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Employee> result = new java.util.ArrayList<ccgprojecttracking.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ProjectDetails_Employee.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ProjectDetails_Employee
	 * @param projectdetails_employee
	 */
	public final void setProjectDetails_Employee(java.util.List<ccgprojecttracking.proxies.Employee> projectdetails_employee)
	{
		setProjectDetails_Employee(getContext(), projectdetails_employee);
	}

	/**
	 * Set value of ProjectDetails_Employee
	 * @param context
	 * @param projectdetails_employee
	 */
	public final void setProjectDetails_Employee(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.Employee> projectdetails_employee)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.Employee proxyObject : projectdetails_employee)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ProjectDetails_Employee.toString(), identifiers);
	}

	/**
	 * @return value of ProjectDetails_ProjectOwner
	 */
	public final ccgprojecttracking.proxies.ProjectOwner getProjectDetails_ProjectOwner() throws com.mendix.core.CoreException
	{
		return getProjectDetails_ProjectOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_ProjectOwner
	 */
	public final ccgprojecttracking.proxies.ProjectOwner getProjectDetails_ProjectOwner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectOwner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_ProjectOwner.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectOwner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_ProjectOwner
	 * @param projectdetails_projectowner
	 */
	public final void setProjectDetails_ProjectOwner(ccgprojecttracking.proxies.ProjectOwner projectdetails_projectowner)
	{
		setProjectDetails_ProjectOwner(getContext(), projectdetails_projectowner);
	}

	/**
	 * Set value of ProjectDetails_ProjectOwner
	 * @param context
	 * @param projectdetails_projectowner
	 */
	public final void setProjectDetails_ProjectOwner(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectOwner projectdetails_projectowner)
	{
		if (projectdetails_projectowner == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_ProjectOwner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_ProjectOwner.toString(), projectdetails_projectowner.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_SME
	 */
	public final java.util.List<ccgprojecttracking.proxies.SME> getProjectDetails_SME() throws com.mendix.core.CoreException
	{
		return getProjectDetails_SME(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_SME
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.SME> getProjectDetails_SME(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.SME> result = new java.util.ArrayList<ccgprojecttracking.proxies.SME>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ProjectDetails_SME.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.SME.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ProjectDetails_SME
	 * @param projectdetails_sme
	 */
	public final void setProjectDetails_SME(java.util.List<ccgprojecttracking.proxies.SME> projectdetails_sme)
	{
		setProjectDetails_SME(getContext(), projectdetails_sme);
	}

	/**
	 * Set value of ProjectDetails_SME
	 * @param context
	 * @param projectdetails_sme
	 */
	public final void setProjectDetails_SME(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.SME> projectdetails_sme)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.SME proxyObject : projectdetails_sme)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ProjectDetails_SME.toString(), identifiers);
	}

	/**
	 * @return value of ProjectDetails_Modified
	 */
	public final java.util.List<ccgprojecttracking.proxies.Modified> getProjectDetails_Modified() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Modified(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Modified
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.Modified> getProjectDetails_Modified(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Modified> result = new java.util.ArrayList<ccgprojecttracking.proxies.Modified>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ProjectDetails_Modified.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.Modified.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ProjectDetails_Modified
	 * @param projectdetails_modified
	 */
	public final void setProjectDetails_Modified(java.util.List<ccgprojecttracking.proxies.Modified> projectdetails_modified)
	{
		setProjectDetails_Modified(getContext(), projectdetails_modified);
	}

	/**
	 * Set value of ProjectDetails_Modified
	 * @param context
	 * @param projectdetails_modified
	 */
	public final void setProjectDetails_Modified(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.Modified> projectdetails_modified)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.Modified proxyObject : projectdetails_modified)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ProjectDetails_Modified.toString(), identifiers);
	}

	/**
	 * @return value of ProjectDetails_Enhancement
	 */
	public final ccgprojecttracking.proxies.Enhancement getProjectDetails_Enhancement() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Enhancement(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Enhancement
	 */
	public final ccgprojecttracking.proxies.Enhancement getProjectDetails_Enhancement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Enhancement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_Enhancement.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Enhancement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_Enhancement
	 * @param projectdetails_enhancement
	 */
	public final void setProjectDetails_Enhancement(ccgprojecttracking.proxies.Enhancement projectdetails_enhancement)
	{
		setProjectDetails_Enhancement(getContext(), projectdetails_enhancement);
	}

	/**
	 * Set value of ProjectDetails_Enhancement
	 * @param context
	 * @param projectdetails_enhancement
	 */
	public final void setProjectDetails_Enhancement(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Enhancement projectdetails_enhancement)
	{
		if (projectdetails_enhancement == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Enhancement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Enhancement.toString(), projectdetails_enhancement.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_Revision
	 */
	public final ccgprojecttracking.proxies.Revision getProjectDetails_Revision() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Revision(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Revision
	 */
	public final ccgprojecttracking.proxies.Revision getProjectDetails_Revision(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Revision result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_Revision.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Revision.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_Revision
	 * @param projectdetails_revision
	 */
	public final void setProjectDetails_Revision(ccgprojecttracking.proxies.Revision projectdetails_revision)
	{
		setProjectDetails_Revision(getContext(), projectdetails_revision);
	}

	/**
	 * Set value of ProjectDetails_Revision
	 * @param context
	 * @param projectdetails_revision
	 */
	public final void setProjectDetails_Revision(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Revision projectdetails_revision)
	{
		if (projectdetails_revision == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Revision.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Revision.toString(), projectdetails_revision.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_Sprint
	 */
	public final ccgprojecttracking.proxies.Sprint getProjectDetails_Sprint() throws com.mendix.core.CoreException
	{
		return getProjectDetails_Sprint(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_Sprint
	 */
	public final ccgprojecttracking.proxies.Sprint getProjectDetails_Sprint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Sprint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_Sprint.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Sprint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_Sprint
	 * @param projectdetails_sprint
	 */
	public final void setProjectDetails_Sprint(ccgprojecttracking.proxies.Sprint projectdetails_sprint)
	{
		setProjectDetails_Sprint(getContext(), projectdetails_sprint);
	}

	/**
	 * Set value of ProjectDetails_Sprint
	 * @param context
	 * @param projectdetails_sprint
	 */
	public final void setProjectDetails_Sprint(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Sprint projectdetails_sprint)
	{
		if (projectdetails_sprint == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Sprint.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_Sprint.toString(), projectdetails_sprint.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_DataArchitect
	 */
	public final ccgprojecttracking.proxies.Employee getProjectDetails_DataArchitect() throws com.mendix.core.CoreException
	{
		return getProjectDetails_DataArchitect(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_DataArchitect
	 */
	public final ccgprojecttracking.proxies.Employee getProjectDetails_DataArchitect(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_DataArchitect.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_DataArchitect
	 * @param projectdetails_dataarchitect
	 */
	public final void setProjectDetails_DataArchitect(ccgprojecttracking.proxies.Employee projectdetails_dataarchitect)
	{
		setProjectDetails_DataArchitect(getContext(), projectdetails_dataarchitect);
	}

	/**
	 * Set value of ProjectDetails_DataArchitect
	 * @param context
	 * @param projectdetails_dataarchitect
	 */
	public final void setProjectDetails_DataArchitect(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee projectdetails_dataarchitect)
	{
		if (projectdetails_dataarchitect == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_DataArchitect.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_DataArchitect.toString(), projectdetails_dataarchitect.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_BusinessCoordinator
	 */
	public final ccgprojecttracking.proxies.Employee getProjectDetails_BusinessCoordinator() throws com.mendix.core.CoreException
	{
		return getProjectDetails_BusinessCoordinator(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_BusinessCoordinator
	 */
	public final ccgprojecttracking.proxies.Employee getProjectDetails_BusinessCoordinator(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProjectDetails_BusinessCoordinator.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProjectDetails_BusinessCoordinator
	 * @param projectdetails_businesscoordinator
	 */
	public final void setProjectDetails_BusinessCoordinator(ccgprojecttracking.proxies.Employee projectdetails_businesscoordinator)
	{
		setProjectDetails_BusinessCoordinator(getContext(), projectdetails_businesscoordinator);
	}

	/**
	 * Set value of ProjectDetails_BusinessCoordinator
	 * @param context
	 * @param projectdetails_businesscoordinator
	 */
	public final void setProjectDetails_BusinessCoordinator(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee projectdetails_businesscoordinator)
	{
		if (projectdetails_businesscoordinator == null)
			getMendixObject().setValue(context, MemberNames.ProjectDetails_BusinessCoordinator.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProjectDetails_BusinessCoordinator.toString(), projectdetails_businesscoordinator.getMendixObject().getId());
	}

	/**
	 * @return value of ProjectDetails_BusinessCo
	 */
	public final java.util.List<ccgprojecttracking.proxies.Employee> getProjectDetails_BusinessCo() throws com.mendix.core.CoreException
	{
		return getProjectDetails_BusinessCo(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectDetails_BusinessCo
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.Employee> getProjectDetails_BusinessCo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Employee> result = new java.util.ArrayList<ccgprojecttracking.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ProjectDetails_BusinessCo.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ProjectDetails_BusinessCo
	 * @param projectdetails_businessco
	 */
	public final void setProjectDetails_BusinessCo(java.util.List<ccgprojecttracking.proxies.Employee> projectdetails_businessco)
	{
		setProjectDetails_BusinessCo(getContext(), projectdetails_businessco);
	}

	/**
	 * Set value of ProjectDetails_BusinessCo
	 * @param context
	 * @param projectdetails_businessco
	 */
	public final void setProjectDetails_BusinessCo(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.Employee> projectdetails_businessco)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.Employee proxyObject : projectdetails_businessco)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ProjectDetails_BusinessCo.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return projectDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.ProjectDetails that = (ccgprojecttracking.proxies.ProjectDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.ProjectDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
