// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class Revision
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject revisionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.Revision";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Rev_ID("Rev_ID"),
		Revision_Description("Revision_Description"),
		Revision_Date("Revision_Date"),
		RevisionReason("RevisionReason"),
		Revision_completedDate("Revision_completedDate"),
		Revision_Task("CCGProjectTracking.Revision_Task"),
		Revision_ProjectDetails("CCGProjectTracking.Revision_ProjectDetails");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Revision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.Revision"));
	}

	protected Revision(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject revisionMendixObject)
	{
		if (revisionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.Revision", revisionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.Revision");

		this.revisionMendixObject = revisionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Revision.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.Revision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.Revision.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.Revision initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.Revision(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.Revision load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.Revision.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.Revision> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Revision> result = new java.util.ArrayList<ccgprojecttracking.proxies.Revision>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.Revision" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.Revision.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Rev_ID
	 */
	public final java.lang.String getRev_ID()
	{
		return getRev_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Rev_ID
	 */
	public final java.lang.String getRev_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Rev_ID.toString());
	}

	/**
	 * Set value of Rev_ID
	 * @param rev_id
	 */
	public final void setRev_ID(java.lang.String rev_id)
	{
		setRev_ID(getContext(), rev_id);
	}

	/**
	 * Set value of Rev_ID
	 * @param context
	 * @param rev_id
	 */
	public final void setRev_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rev_id)
	{
		getMendixObject().setValue(context, MemberNames.Rev_ID.toString(), rev_id);
	}

	/**
	 * @return value of Revision_Description
	 */
	public final java.lang.String getRevision_Description()
	{
		return getRevision_Description(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Description
	 */
	public final java.lang.String getRevision_Description(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Revision_Description.toString());
	}

	/**
	 * Set value of Revision_Description
	 * @param revision_description
	 */
	public final void setRevision_Description(java.lang.String revision_description)
	{
		setRevision_Description(getContext(), revision_description);
	}

	/**
	 * Set value of Revision_Description
	 * @param context
	 * @param revision_description
	 */
	public final void setRevision_Description(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revision_description)
	{
		getMendixObject().setValue(context, MemberNames.Revision_Description.toString(), revision_description);
	}

	/**
	 * @return value of Revision_Date
	 */
	public final java.util.Date getRevision_Date()
	{
		return getRevision_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Date
	 */
	public final java.util.Date getRevision_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Revision_Date.toString());
	}

	/**
	 * Set value of Revision_Date
	 * @param revision_date
	 */
	public final void setRevision_Date(java.util.Date revision_date)
	{
		setRevision_Date(getContext(), revision_date);
	}

	/**
	 * Set value of Revision_Date
	 * @param context
	 * @param revision_date
	 */
	public final void setRevision_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date revision_date)
	{
		getMendixObject().setValue(context, MemberNames.Revision_Date.toString(), revision_date);
	}

	/**
	 * @return value of RevisionReason
	 */
	public final java.lang.String getRevisionReason()
	{
		return getRevisionReason(getContext());
	}

	/**
	 * @param context
	 * @return value of RevisionReason
	 */
	public final java.lang.String getRevisionReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RevisionReason.toString());
	}

	/**
	 * Set value of RevisionReason
	 * @param revisionreason
	 */
	public final void setRevisionReason(java.lang.String revisionreason)
	{
		setRevisionReason(getContext(), revisionreason);
	}

	/**
	 * Set value of RevisionReason
	 * @param context
	 * @param revisionreason
	 */
	public final void setRevisionReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String revisionreason)
	{
		getMendixObject().setValue(context, MemberNames.RevisionReason.toString(), revisionreason);
	}

	/**
	 * @return value of Revision_completedDate
	 */
	public final java.util.Date getRevision_completedDate()
	{
		return getRevision_completedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_completedDate
	 */
	public final java.util.Date getRevision_completedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Revision_completedDate.toString());
	}

	/**
	 * Set value of Revision_completedDate
	 * @param revision_completeddate
	 */
	public final void setRevision_completedDate(java.util.Date revision_completeddate)
	{
		setRevision_completedDate(getContext(), revision_completeddate);
	}

	/**
	 * Set value of Revision_completedDate
	 * @param context
	 * @param revision_completeddate
	 */
	public final void setRevision_completedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date revision_completeddate)
	{
		getMendixObject().setValue(context, MemberNames.Revision_completedDate.toString(), revision_completeddate);
	}

	/**
	 * @return value of Revision_Task
	 */
	public final ccgprojecttracking.proxies.Task getRevision_Task() throws com.mendix.core.CoreException
	{
		return getRevision_Task(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_Task
	 */
	public final ccgprojecttracking.proxies.Task getRevision_Task(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Task result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revision_Task.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Task.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Revision_Task
	 * @param revision_task
	 */
	public final void setRevision_Task(ccgprojecttracking.proxies.Task revision_task)
	{
		setRevision_Task(getContext(), revision_task);
	}

	/**
	 * Set value of Revision_Task
	 * @param context
	 * @param revision_task
	 */
	public final void setRevision_Task(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Task revision_task)
	{
		if (revision_task == null)
			getMendixObject().setValue(context, MemberNames.Revision_Task.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Revision_Task.toString(), revision_task.getMendixObject().getId());
	}

	/**
	 * @return value of Revision_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getRevision_ProjectDetails() throws com.mendix.core.CoreException
	{
		return getRevision_ProjectDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Revision_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getRevision_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Revision_ProjectDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Revision_ProjectDetails
	 * @param revision_projectdetails
	 */
	public final void setRevision_ProjectDetails(ccgprojecttracking.proxies.ProjectDetails revision_projectdetails)
	{
		setRevision_ProjectDetails(getContext(), revision_projectdetails);
	}

	/**
	 * Set value of Revision_ProjectDetails
	 * @param context
	 * @param revision_projectdetails
	 */
	public final void setRevision_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectDetails revision_projectdetails)
	{
		if (revision_projectdetails == null)
			getMendixObject().setValue(context, MemberNames.Revision_ProjectDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Revision_ProjectDetails.toString(), revision_projectdetails.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return revisionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.Revision that = (ccgprojecttracking.proxies.Revision) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.Revision";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
