// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public enum Sp_percent
{
	_0(new java.lang.String[][] { new java.lang.String[] { "en_US", "0" } }),
	_10(new java.lang.String[][] { new java.lang.String[] { "en_US", "10" } }),
	_20(new java.lang.String[][] { new java.lang.String[] { "en_US", "20" } }),
	_30(new java.lang.String[][] { new java.lang.String[] { "en_US", "30" } }),
	_40(new java.lang.String[][] { new java.lang.String[] { "en_US", "40" } }),
	_50(new java.lang.String[][] { new java.lang.String[] { "en_US", "50" } }),
	_60(new java.lang.String[][] { new java.lang.String[] { "en_US", "60" } }),
	_70(new java.lang.String[][] { new java.lang.String[] { "en_US", "70" } }),
	_80(new java.lang.String[][] { new java.lang.String[] { "en_US", "80" } }),
	_90(new java.lang.String[][] { new java.lang.String[] { "en_US", "90" } }),
	_100(new java.lang.String[][] { new java.lang.String[] { "en_US", "100" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Sp_percent(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
