// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class Task
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.Task";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskID("TaskID"),
		Current_Phase("Current_Phase"),
		Task_Status("Task_Status"),
		Task_per_completed("Task_per_completed"),
		Task_Start_Date("Task_Start_Date"),
		Task_End_Date("Task_End_Date"),
		Task_Description("Task_Description"),
		ESR_Id("ESR_Id"),
		Task_ProjectDetails("CCGProjectTracking.Task_ProjectDetails"),
		Task_Employee("CCGProjectTracking.Task_Employee"),
		Task_EventDetails("CCGProjectTracking.Task_EventDetails"),
		Task_Enhancement("CCGProjectTracking.Task_Enhancement"),
		Task_Revision("CCGProjectTracking.Task_Revision"),
		Task_Sprint("CCGProjectTracking.Task_Sprint"),
		Task_Employee_2("CCGProjectTracking.Task_Employee_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Task(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.Task"));
	}

	protected Task(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskMendixObject)
	{
		if (taskMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.Task", taskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.Task");

		this.taskMendixObject = taskMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Task.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.Task initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.Task.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.Task initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.Task(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.Task load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.Task.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.Task> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Task> result = new java.util.ArrayList<ccgprojecttracking.proxies.Task>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.Task" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.Task.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TaskID
	 */
	public final java.lang.String getTaskID()
	{
		return getTaskID(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskID
	 */
	public final java.lang.String getTaskID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskID.toString());
	}

	/**
	 * Set value of TaskID
	 * @param taskid
	 */
	public final void setTaskID(java.lang.String taskid)
	{
		setTaskID(getContext(), taskid);
	}

	/**
	 * Set value of TaskID
	 * @param context
	 * @param taskid
	 */
	public final void setTaskID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskid)
	{
		getMendixObject().setValue(context, MemberNames.TaskID.toString(), taskid);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase()
	{
		return getCurrent_Phase(getContext());
	}

	/**
	 * @param context
	 * @return value of Current_Phase
	 */
	public final ccgprojecttracking.proxies.Currentphase getCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Current_Phase.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.Currentphase.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Current_Phase
	 * @param current_phase
	 */
	public final void setCurrent_Phase(ccgprojecttracking.proxies.Currentphase current_phase)
	{
		setCurrent_Phase(getContext(), current_phase);
	}

	/**
	 * Set value of Current_Phase
	 * @param context
	 * @param current_phase
	 */
	public final void setCurrent_Phase(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Currentphase current_phase)
	{
		if (current_phase != null)
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), current_phase.toString());
		else
			getMendixObject().setValue(context, MemberNames.Current_Phase.toString(), null);
	}

	/**
	 * Set value of Task_Status
	 * @param task_status
	 */
	public final ccgprojecttracking.proxies.TS getTask_Status()
	{
		return getTask_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Status
	 */
	public final ccgprojecttracking.proxies.TS getTask_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Task_Status.toString());
		if (obj == null)
			return null;

		return ccgprojecttracking.proxies.TS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Task_Status
	 * @param task_status
	 */
	public final void setTask_Status(ccgprojecttracking.proxies.TS task_status)
	{
		setTask_Status(getContext(), task_status);
	}

	/**
	 * Set value of Task_Status
	 * @param context
	 * @param task_status
	 */
	public final void setTask_Status(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.TS task_status)
	{
		if (task_status != null)
			getMendixObject().setValue(context, MemberNames.Task_Status.toString(), task_status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Task_Status.toString(), null);
	}

	/**
	 * @return value of Task_per_completed
	 */
	public final java.lang.Integer getTask_per_completed()
	{
		return getTask_per_completed(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_per_completed
	 */
	public final java.lang.Integer getTask_per_completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Task_per_completed.toString());
	}

	/**
	 * Set value of Task_per_completed
	 * @param task_per_completed
	 */
	public final void setTask_per_completed(java.lang.Integer task_per_completed)
	{
		setTask_per_completed(getContext(), task_per_completed);
	}

	/**
	 * Set value of Task_per_completed
	 * @param context
	 * @param task_per_completed
	 */
	public final void setTask_per_completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer task_per_completed)
	{
		getMendixObject().setValue(context, MemberNames.Task_per_completed.toString(), task_per_completed);
	}

	/**
	 * @return value of Task_Start_Date
	 */
	public final java.util.Date getTask_Start_Date()
	{
		return getTask_Start_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Start_Date
	 */
	public final java.util.Date getTask_Start_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Task_Start_Date.toString());
	}

	/**
	 * Set value of Task_Start_Date
	 * @param task_start_date
	 */
	public final void setTask_Start_Date(java.util.Date task_start_date)
	{
		setTask_Start_Date(getContext(), task_start_date);
	}

	/**
	 * Set value of Task_Start_Date
	 * @param context
	 * @param task_start_date
	 */
	public final void setTask_Start_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date task_start_date)
	{
		getMendixObject().setValue(context, MemberNames.Task_Start_Date.toString(), task_start_date);
	}

	/**
	 * @return value of Task_End_Date
	 */
	public final java.util.Date getTask_End_Date()
	{
		return getTask_End_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_End_Date
	 */
	public final java.util.Date getTask_End_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Task_End_Date.toString());
	}

	/**
	 * Set value of Task_End_Date
	 * @param task_end_date
	 */
	public final void setTask_End_Date(java.util.Date task_end_date)
	{
		setTask_End_Date(getContext(), task_end_date);
	}

	/**
	 * Set value of Task_End_Date
	 * @param context
	 * @param task_end_date
	 */
	public final void setTask_End_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date task_end_date)
	{
		getMendixObject().setValue(context, MemberNames.Task_End_Date.toString(), task_end_date);
	}

	/**
	 * @return value of Task_Description
	 */
	public final java.lang.String getTask_Description()
	{
		return getTask_Description(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Description
	 */
	public final java.lang.String getTask_Description(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Task_Description.toString());
	}

	/**
	 * Set value of Task_Description
	 * @param task_description
	 */
	public final void setTask_Description(java.lang.String task_description)
	{
		setTask_Description(getContext(), task_description);
	}

	/**
	 * Set value of Task_Description
	 * @param context
	 * @param task_description
	 */
	public final void setTask_Description(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String task_description)
	{
		getMendixObject().setValue(context, MemberNames.Task_Description.toString(), task_description);
	}

	/**
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id()
	{
		return getESR_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of ESR_Id
	 */
	public final java.lang.String getESR_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ESR_Id.toString());
	}

	/**
	 * Set value of ESR_Id
	 * @param esr_id
	 */
	public final void setESR_Id(java.lang.String esr_id)
	{
		setESR_Id(getContext(), esr_id);
	}

	/**
	 * Set value of ESR_Id
	 * @param context
	 * @param esr_id
	 */
	public final void setESR_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String esr_id)
	{
		getMendixObject().setValue(context, MemberNames.ESR_Id.toString(), esr_id);
	}

	/**
	 * @return value of Task_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getTask_ProjectDetails() throws com.mendix.core.CoreException
	{
		return getTask_ProjectDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_ProjectDetails
	 */
	public final ccgprojecttracking.proxies.ProjectDetails getTask_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.ProjectDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_ProjectDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.ProjectDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_ProjectDetails
	 * @param task_projectdetails
	 */
	public final void setTask_ProjectDetails(ccgprojecttracking.proxies.ProjectDetails task_projectdetails)
	{
		setTask_ProjectDetails(getContext(), task_projectdetails);
	}

	/**
	 * Set value of Task_ProjectDetails
	 * @param context
	 * @param task_projectdetails
	 */
	public final void setTask_ProjectDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.ProjectDetails task_projectdetails)
	{
		if (task_projectdetails == null)
			getMendixObject().setValue(context, MemberNames.Task_ProjectDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_ProjectDetails.toString(), task_projectdetails.getMendixObject().getId());
	}

	/**
	 * @return value of Task_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getTask_Employee() throws com.mendix.core.CoreException
	{
		return getTask_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Employee
	 */
	public final ccgprojecttracking.proxies.Employee getTask_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_Employee.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_Employee
	 * @param task_employee
	 */
	public final void setTask_Employee(ccgprojecttracking.proxies.Employee task_employee)
	{
		setTask_Employee(getContext(), task_employee);
	}

	/**
	 * Set value of Task_Employee
	 * @param context
	 * @param task_employee
	 */
	public final void setTask_Employee(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee task_employee)
	{
		if (task_employee == null)
			getMendixObject().setValue(context, MemberNames.Task_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_Employee.toString(), task_employee.getMendixObject().getId());
	}

	/**
	 * @return value of Task_EventDetails
	 */
	public final ccgprojecttracking.proxies.EventDetails getTask_EventDetails() throws com.mendix.core.CoreException
	{
		return getTask_EventDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_EventDetails
	 */
	public final ccgprojecttracking.proxies.EventDetails getTask_EventDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.EventDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_EventDetails.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.EventDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_EventDetails
	 * @param task_eventdetails
	 */
	public final void setTask_EventDetails(ccgprojecttracking.proxies.EventDetails task_eventdetails)
	{
		setTask_EventDetails(getContext(), task_eventdetails);
	}

	/**
	 * Set value of Task_EventDetails
	 * @param context
	 * @param task_eventdetails
	 */
	public final void setTask_EventDetails(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.EventDetails task_eventdetails)
	{
		if (task_eventdetails == null)
			getMendixObject().setValue(context, MemberNames.Task_EventDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_EventDetails.toString(), task_eventdetails.getMendixObject().getId());
	}

	/**
	 * @return value of Task_Enhancement
	 */
	public final ccgprojecttracking.proxies.Enhancement getTask_Enhancement() throws com.mendix.core.CoreException
	{
		return getTask_Enhancement(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Enhancement
	 */
	public final ccgprojecttracking.proxies.Enhancement getTask_Enhancement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Enhancement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_Enhancement.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Enhancement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_Enhancement
	 * @param task_enhancement
	 */
	public final void setTask_Enhancement(ccgprojecttracking.proxies.Enhancement task_enhancement)
	{
		setTask_Enhancement(getContext(), task_enhancement);
	}

	/**
	 * Set value of Task_Enhancement
	 * @param context
	 * @param task_enhancement
	 */
	public final void setTask_Enhancement(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Enhancement task_enhancement)
	{
		if (task_enhancement == null)
			getMendixObject().setValue(context, MemberNames.Task_Enhancement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_Enhancement.toString(), task_enhancement.getMendixObject().getId());
	}

	/**
	 * @return value of Task_Revision
	 */
	public final ccgprojecttracking.proxies.Revision getTask_Revision() throws com.mendix.core.CoreException
	{
		return getTask_Revision(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Revision
	 */
	public final ccgprojecttracking.proxies.Revision getTask_Revision(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Revision result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_Revision.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Revision.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_Revision
	 * @param task_revision
	 */
	public final void setTask_Revision(ccgprojecttracking.proxies.Revision task_revision)
	{
		setTask_Revision(getContext(), task_revision);
	}

	/**
	 * Set value of Task_Revision
	 * @param context
	 * @param task_revision
	 */
	public final void setTask_Revision(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Revision task_revision)
	{
		if (task_revision == null)
			getMendixObject().setValue(context, MemberNames.Task_Revision.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_Revision.toString(), task_revision.getMendixObject().getId());
	}

	/**
	 * @return value of Task_Sprint
	 */
	public final ccgprojecttracking.proxies.Sprint getTask_Sprint() throws com.mendix.core.CoreException
	{
		return getTask_Sprint(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Sprint
	 */
	public final ccgprojecttracking.proxies.Sprint getTask_Sprint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Sprint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Task_Sprint.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Sprint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Task_Sprint
	 * @param task_sprint
	 */
	public final void setTask_Sprint(ccgprojecttracking.proxies.Sprint task_sprint)
	{
		setTask_Sprint(getContext(), task_sprint);
	}

	/**
	 * Set value of Task_Sprint
	 * @param context
	 * @param task_sprint
	 */
	public final void setTask_Sprint(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Sprint task_sprint)
	{
		if (task_sprint == null)
			getMendixObject().setValue(context, MemberNames.Task_Sprint.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Task_Sprint.toString(), task_sprint.getMendixObject().getId());
	}

	/**
	 * @return value of Task_Employee_2
	 */
	public final java.util.List<ccgprojecttracking.proxies.Employee> getTask_Employee_2() throws com.mendix.core.CoreException
	{
		return getTask_Employee_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Task_Employee_2
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.Employee> getTask_Employee_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Employee> result = new java.util.ArrayList<ccgprojecttracking.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Task_Employee_2.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Task_Employee_2
	 * @param task_employee_2
	 */
	public final void setTask_Employee_2(java.util.List<ccgprojecttracking.proxies.Employee> task_employee_2)
	{
		setTask_Employee_2(getContext(), task_employee_2);
	}

	/**
	 * Set value of Task_Employee_2
	 * @param context
	 * @param task_employee_2
	 */
	public final void setTask_Employee_2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.Employee> task_employee_2)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.Employee proxyObject : task_employee_2)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Task_Employee_2.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.Task that = (ccgprojecttracking.proxies.Task) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.Task";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
