// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ccgprojecttracking.proxies;

public class Team
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject teamMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CCGProjectTracking.Team";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Team_ID("Team_ID"),
		EMP_ROLE("EMP_ROLE"),
		Team_Created_Date("Team_Created_Date"),
		NewTeamName("NewTeamName"),
		NewTeam_ChangedDate("NewTeam_ChangedDate"),
		Team_Employee("CCGProjectTracking.Team_Employee"),
		Team_Employee_2("CCGProjectTracking.Team_Employee_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Team(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "CCGProjectTracking.Team"));
	}

	protected Team(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject teamMendixObject)
	{
		if (teamMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("CCGProjectTracking.Team", teamMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a CCGProjectTracking.Team");

		this.teamMendixObject = teamMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Team.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ccgprojecttracking.proxies.Team initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ccgprojecttracking.proxies.Team.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ccgprojecttracking.proxies.Team initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ccgprojecttracking.proxies.Team(context, mendixObject);
	}

	public static ccgprojecttracking.proxies.Team load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ccgprojecttracking.proxies.Team.initialize(context, mendixObject);
	}

	public static java.util.List<ccgprojecttracking.proxies.Team> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Team> result = new java.util.ArrayList<ccgprojecttracking.proxies.Team>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//CCGProjectTracking.Team" + xpathConstraint))
			result.add(ccgprojecttracking.proxies.Team.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Team_ID
	 */
	public final java.lang.String getTeam_ID()
	{
		return getTeam_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_ID
	 */
	public final java.lang.String getTeam_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Team_ID.toString());
	}

	/**
	 * Set value of Team_ID
	 * @param team_id
	 */
	public final void setTeam_ID(java.lang.String team_id)
	{
		setTeam_ID(getContext(), team_id);
	}

	/**
	 * Set value of Team_ID
	 * @param context
	 * @param team_id
	 */
	public final void setTeam_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String team_id)
	{
		getMendixObject().setValue(context, MemberNames.Team_ID.toString(), team_id);
	}

	/**
	 * @return value of EMP_ROLE
	 */
	public final java.lang.String getEMP_ROLE()
	{
		return getEMP_ROLE(getContext());
	}

	/**
	 * @param context
	 * @return value of EMP_ROLE
	 */
	public final java.lang.String getEMP_ROLE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EMP_ROLE.toString());
	}

	/**
	 * Set value of EMP_ROLE
	 * @param emp_role
	 */
	public final void setEMP_ROLE(java.lang.String emp_role)
	{
		setEMP_ROLE(getContext(), emp_role);
	}

	/**
	 * Set value of EMP_ROLE
	 * @param context
	 * @param emp_role
	 */
	public final void setEMP_ROLE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emp_role)
	{
		getMendixObject().setValue(context, MemberNames.EMP_ROLE.toString(), emp_role);
	}

	/**
	 * @return value of Team_Created_Date
	 */
	public final java.util.Date getTeam_Created_Date()
	{
		return getTeam_Created_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_Created_Date
	 */
	public final java.util.Date getTeam_Created_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Team_Created_Date.toString());
	}

	/**
	 * Set value of Team_Created_Date
	 * @param team_created_date
	 */
	public final void setTeam_Created_Date(java.util.Date team_created_date)
	{
		setTeam_Created_Date(getContext(), team_created_date);
	}

	/**
	 * Set value of Team_Created_Date
	 * @param context
	 * @param team_created_date
	 */
	public final void setTeam_Created_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date team_created_date)
	{
		getMendixObject().setValue(context, MemberNames.Team_Created_Date.toString(), team_created_date);
	}

	/**
	 * @return value of NewTeamName
	 */
	public final java.lang.String getNewTeamName()
	{
		return getNewTeamName(getContext());
	}

	/**
	 * @param context
	 * @return value of NewTeamName
	 */
	public final java.lang.String getNewTeamName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NewTeamName.toString());
	}

	/**
	 * Set value of NewTeamName
	 * @param newteamname
	 */
	public final void setNewTeamName(java.lang.String newteamname)
	{
		setNewTeamName(getContext(), newteamname);
	}

	/**
	 * Set value of NewTeamName
	 * @param context
	 * @param newteamname
	 */
	public final void setNewTeamName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String newteamname)
	{
		getMendixObject().setValue(context, MemberNames.NewTeamName.toString(), newteamname);
	}

	/**
	 * @return value of NewTeam_ChangedDate
	 */
	public final java.util.Date getNewTeam_ChangedDate()
	{
		return getNewTeam_ChangedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of NewTeam_ChangedDate
	 */
	public final java.util.Date getNewTeam_ChangedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.NewTeam_ChangedDate.toString());
	}

	/**
	 * Set value of NewTeam_ChangedDate
	 * @param newteam_changeddate
	 */
	public final void setNewTeam_ChangedDate(java.util.Date newteam_changeddate)
	{
		setNewTeam_ChangedDate(getContext(), newteam_changeddate);
	}

	/**
	 * Set value of NewTeam_ChangedDate
	 * @param context
	 * @param newteam_changeddate
	 */
	public final void setNewTeam_ChangedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date newteam_changeddate)
	{
		getMendixObject().setValue(context, MemberNames.NewTeam_ChangedDate.toString(), newteam_changeddate);
	}

	/**
	 * @return value of Team_Employee
	 */
	public final java.util.List<ccgprojecttracking.proxies.Employee> getTeam_Employee() throws com.mendix.core.CoreException
	{
		return getTeam_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_Employee
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<ccgprojecttracking.proxies.Employee> getTeam_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<ccgprojecttracking.proxies.Employee> result = new java.util.ArrayList<ccgprojecttracking.proxies.Employee>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Team_Employee.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(ccgprojecttracking.proxies.Employee.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Team_Employee
	 * @param team_employee
	 */
	public final void setTeam_Employee(java.util.List<ccgprojecttracking.proxies.Employee> team_employee)
	{
		setTeam_Employee(getContext(), team_employee);
	}

	/**
	 * Set value of Team_Employee
	 * @param context
	 * @param team_employee
	 */
	public final void setTeam_Employee(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<ccgprojecttracking.proxies.Employee> team_employee)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (ccgprojecttracking.proxies.Employee proxyObject : team_employee)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Team_Employee.toString(), identifiers);
	}

	/**
	 * @return value of Team_Employee_2
	 */
	public final ccgprojecttracking.proxies.Employee getTeam_Employee_2() throws com.mendix.core.CoreException
	{
		return getTeam_Employee_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Team_Employee_2
	 */
	public final ccgprojecttracking.proxies.Employee getTeam_Employee_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ccgprojecttracking.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Team_Employee_2.toString());
		if (identifier != null)
			result = ccgprojecttracking.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Team_Employee_2
	 * @param team_employee_2
	 */
	public final void setTeam_Employee_2(ccgprojecttracking.proxies.Employee team_employee_2)
	{
		setTeam_Employee_2(getContext(), team_employee_2);
	}

	/**
	 * Set value of Team_Employee_2
	 * @param context
	 * @param team_employee_2
	 */
	public final void setTeam_Employee_2(com.mendix.systemwideinterfaces.core.IContext context, ccgprojecttracking.proxies.Employee team_employee_2)
	{
		if (team_employee_2 == null)
			getMendixObject().setValue(context, MemberNames.Team_Employee_2.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Team_Employee_2.toString(), team_employee_2.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return teamMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ccgprojecttracking.proxies.Team that = (ccgprojecttracking.proxies.Team) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "CCGProjectTracking.Team";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
